### ISSUE TITLE
Preserve better browser compatibility by replacing Array.prototype.at

### ISSUE THREAD

**Issue by 87xie** [unjs/rou3#105]
### Describe the feature

I noticed the pull request https://github.com/unjs/destr/pull/102 in the `destr` repository, which replaces the `String.prototype.at` to improve browser compatibility. Since `Array.prototype.at` is used in `radix3` and its support is similar to `String.prototype.at`, should we replace `sections.at(-1)` with `sections[sections.length - 1]` ?

related information links

- https://github.com/unjs/radix3/blob/v1/src/router.ts#L176
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at#browser_compatibility
- https://caniuse.com/mdn-javascript_builtins_array_at

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Next version (rou3) is currently not using `.at` at least
