### ISSUE TITLE
Update npm scripts to simplify the benchmark command

### ISSUE THREAD

**Issue by 87xie** [unjs/rou3#109]
### Describe the feature

The recent rewrite #107 has significantly boosted performance!

Following these changes, it appears that the current benchmark scripts in `package.json` are outdated.

Could we update these scripts to reflect recent changes and ensure smooth execution of benchmark tasks? Additionally, it might be beneficial to clean up unused dev-dependencies such as `benchmark`, `autocannon`, etc.

Thank you for your attention to this matter!

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Thanks for suggestion. [benchmarks dir](https://github.com/unjs/rou3/tree/main/benchmark) includes detailed commands. (there is one top level pkg command but i probably remove it once automated via CI)
