### ISSUE TITLE
Rou3 incorrect matching strategy

### ISSUE THREAD

**Issue by medz** [unjs/rou3#119]
### Environment

Bun

### Reproduction

```typescript
import { createRouter, addRoute, findRoute } from "rou3";

const router = createRouter();

addRoute(
  router,
  "get",
  "/files/:dir/:filename.:format,v:version",
  "Mixed route"
);

console.log(findRoute(router, "get", "/files/demo.yaml.dart,v1"));
```

### Describe the bug

It is due to https://github.com/unjs/rou3/blob/main/src/operations/find.ts#L62 Resulting from incorrect behavior!

Under normal circumstances, this route should not have any matching results!

### Logs

```sh
14 |   for (const [index, name] of paramsMap) {
15 |     const segment = index < 0 ? segments.slice(-1 * index).join("/") : segments[index];
16 |     if (typeof name === "string") {
17 |       params[name] = segment;
18 |     } else {
19 |       const match = segment.match(name);
                         ^
TypeError: undefined is not an object (evaluating 'segment.match')
      at getMatchParams (/Users/seven/workspace/test/node_modules/rou3/dist/index.mjs:19:21)
      at /Users/seven/workspace/test/node_modules/rou3/dist/index.mjs:113:29
      at map (:1:11)
      at /Users/seven/workspace/test/demo.ts:26:13

Bun v1.1.18 (macOS arm64)
```

**Comment by medz** [comment]
The root cause of the bug 👉 https://github.com/unjs/rou3/issues/84#issuecomment-2226853375

**Comment by pi0** [comment]
with https://github.com/unjs/rou3/pull/123 last segments will be required unless specified with `*` or `**` (optional), i hope you are happy with this middle ground solution.

**Comment by pi0** [comment]
Thanks for sharing testing result. I belove you might want to register `/demo/:name` + `/demo` routes in case above and `/demo` will be matching base:

```js
import { createRouter, addRoute, findRoute } from "rou3";

const router = createRouter();

addRoute(router, "get", "/demo/:name", 1);
addRoute(router, "get", "/demo", 2);
addRoute(router, "get", "/demo/**", 3);

console.log(findRoute(router, "get", "/demo")); // 2
console.log(findRoute(router, "get", "/demo/test")); // 1 name: test
console.log(findRoute(router, "get", "/demo/test/bar")); // 3 _: test/bar

```

We could actually do more extensive runtime checks to iterate all array but it will cause performance degradations. 

Please let me know if found any other issues 👍🏼

**Comment by medz** [comment]
@pi0 Thank you for your reply, but there are some special circumstances when using Rou3 downstream.
Developers often allow mechanisms to override routing (although this should not happen as developers), but typically web framework developers allow their users to tolerate such error issues. When registering routes repeatedly, it should be indicated that this is an override behavior (unless otherwise specified).

I found that the specificity of using rou3 as a middleware in the UnJS ecosystem (H3) may be in line with this feature, but H3 also allows for the generation of this mechanism, which only matches the first data at a time without clear indication. As a result, routes that have been repeatedly registered are not included in the matching content, but the corresponding content has been saved.

This seems to be a waste of memory.

**Comment by pi0** [comment]
We store all cases in an array for the purpose of pattern matching `findAllRoutes` where we want all possibly matching routes.

**Comment by medz** [comment]
I think issuing a warning message is a great solution
