### ISSUE TITLE
There seems to be a problem with `findAllRoutes` boundaries

### ISSUE THREAD

**Issue by medz** [unjs/rou3#124]
### Environment

Bun

### Reproduction

```typescript
import { createRouter, addRoute, findAllRoutes } from "rou3";

const router = createRouter();

addRoute(router, "get", "/path", "Static");
addRoute(router, "get", "/path/:name", "Param");

console.log(findAllRoutes(router, "get", "/path"));
```

### Describe the bug

Register two routes: `/path` and `/path/:name`, or add another route: `/path/:bar/:qaz`

Use `/path` to call `findAllRoutes`, and the result includes `/path/:name` and `/path/:bar/:qaz` routes.

### Logs

```sh
[
  {
    data: "Param",
    params: {
      name: undefined,
    },
  }, {
    data: "Static",
    params: undefined,
  }
]
```

**Comment by pi0** [comment]
Thanks for report i kinda forgot to do it for findAll too before release. We need to do similar fix of #123. (feel free to PR)
