### ISSUE TITLE
URL pattern support

### ISSUE THREAD

**Issue by pi0** [unjs/rou3#51]
Investigating [URL Pattern API compatibility](https://developer.mozilla.org/en-US/docs/Web/API/URL_Pattern_API). 

There are different goals for a fast route matcher (radix3) and a general purpose URL pattern matching standard. I still think we might somehow make a compatibility layer to convert the URL pattern to radix3. Additional regex checks (after fast initial phase) can be applied using the `URLPattern` class api.

**Comment by aquapi** [comment]
The only reasonable URL patterns are wildcards and URL parameters, which we can basically implement with a radix tree. RegExp is not fast, and it may decreases performance on other runtimes as well (especially Bun because for some reason JSC has really bad RegExp implementation).

**Comment by Tofandel** [comment]
Could params be expanded with regex at least? This would avoid a general performance impact (unless all defined routes make use of this).

Sometimes a small tradeoff is necessary
Without this feature a lot of uses cases are simply not possible

Imagine if apache, nginx or vue-router didn't ship with regex support.. This is always a core feature of any router implementation

**Comment by pi0** [comment]
you can always make regex matching on top of simple patterns. please feel free to open a new issue sharing some server real examples that aren't possible today.

**Comment by aquapi** [comment]
@Tofandel Most frameworks in other languages don't support regexes as well (uWS, Gin, Actix, ...).
If you want more patterns you can always extract from their captured parameters.

**Comment by kjjd84** [comment]
duplicate of https://github.com/oven-sh/bun/issues/2286
