### ISSUE TITLE
Is there a way to ignore query parameters?

### ISSUE THREAD

**Issue by Eliasyoussef47** [unjs/rou3#54]
### Environment

Node version: 18.15.0
Package version: 1.0.1

### Reproduction

```ts
import { createRouter } from 'radix3';

const routes = ['/', '/login'];

const skipRoutes = createRouter({ strictTrailingSlash: false });
routes.forEach((e) => skipRoutes.insert(e, {}));

const result = skipRoutes.lookup('/login?foo=1234&bar=1234');

console.log(result); // null
```

### Describe the bug

The `lookup` method doesn't match routes with query params with the ones that don't have query params.

**Comment by pi0** [comment]
Canceled because of the reasons mentioned in https://github.com/unjs/rou3/pull/61#issuecomment-2213488592
