### ISSUE TITLE
Get previous payload from url that have :placeholder

### ISSUE THREAD

**Issue by demosofa** [unjs/rou3#60]
### Describe the feature

I have problem relating to get and update the payload of existed route. I thought like any url that doesn't have :placeholder, I could access the RadixRouter.ctx.staticRoutesMap to get the payload from data through key of url that had :placeholder. But it was undefined and I console.log the staticRoutesMap and the key I want was an emty object. If u ask me why I didn't use lookup because it could mess up with other routes both new and old.

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Hi. You should use `.looup` in radix3 (legacy) and `findRoute` in rou3 (next version) to access platholders only. `staticRoutesMap` is an internal state.
