### ISSUE TITLE
Delete nodes that have no data

### ISSUE THREAD

**Issue by AndrewWalsh** [unjs/rou3#78]
### Describe the feature

Hi there,

At present, removing a node does not prune the tree. Data is deleted, but nodes are not.

I created a function that can do this here https://github.com/AndrewWalsh/openapi-spec-generator/blob/main/src/store-helpers/prune-router.ts (would need to be adapted)

Is this something you think would be worth including?

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Surely PR welcome!

**Comment by AndrewWalsh** [comment]
@pi0 Have this on my backlog but will try to get round to this 👍

**Comment by pi0** [comment]
Hi @AndrewWalsh with #107 i suppose we do proper cleanup but if you have spotted similar issues feel free to raise a PR or just ping me to investigate 👍🏼
