### ISSUE TITLE
`/test` does not match `/test/**` and `/test/*` patterns as fallback

### ISSUE THREAD

**Issue by ToBinio** [unjs/rou3#84]
### Environment

node 20 and bun

### Reproduction

```ts
const router = createRouter();

router.insert("/test/**:test", { payload: "wildcard" });

console.log([
  router.lookup("/test")
]);

```

output: `[ null ]`

expected: `[ { payload: 'wildcard', params: { test: '' } } ]`

### Describe the bug

router does not match `**` as nothing instead requires some value

### Additional context

This does only happen when `**` is not the only part.

`/**` does match `/`
but 
`/test/**` does not match `/test/`

This behavior is not present in the `matcher`
for the matcher there are also tests that check if `**` matches `""`

### possible fix

I also played around a bit and tried fixing it myself and ended up with this addition to the `lookup()` function:

```ts
  if (node && node.data == null && node.wildcardChildNode) {
    node = node.wildcardChildNode;
    params[node.paramName || "_"] = "";
    paramsFound = true;
  }
```

tbh I do not completely understand how the lookup works that's why I am not opening a PR right now

**Comment by medz** [comment]
@pi0 Request fallback! `/test/*` should not be used as a fallback path for `/test`! This is a wrong behavior!

I encountered a lot of such unexpected matching of wrong routes when using rou3! I started using `radix3` again, and rou3 has a lot of unexpected wrong implementations! For example #119

**Comment by medz** [comment]
If I need the correct route fallback, I will register `/test` and `test/**` instead of choosing `/test/*` for me. This will result in the abnormal `/test/:name` handler parameters not being available! rou3 code is very concise, which is great! But there are a lot of abnormal expected behaviors in it, and even the tests are written according to abnormal expected behaviors!
