### ISSUE TITLE
router performance analyzes

### ISSUE THREAD

**Issue by pi0** [unjs/rou3#85]
Radix3 matcher is fairly faster than enough even one a single core laptop CPU ([benchmarks](https://github.com/unjs/radix3/tree/main/benchmark)) and real overhead always is the application logic. However it is a never ending dicussion about radix3 being compared to XYZ also.

My main point of this tracker is to investigate if there are any details in radix3 itself which could potentially be improved (apple-to-apple) but I guess it would make numbers better for apple-to-orange comparations

**Comment by pi0** [comment]
Benchmarks added as part of #107

**Comment by pi0** [comment]
Yep. Also h3 itself in v2 will be web native so numbers for Bun/Deno will definitely change  🚀

**Comment by pmbanugo** [comment]
When will the v2 likely happen? i couldn't find a roadmap, i was just curious if it'll happen this summer

**Comment by pi0** [comment]
v2 is rou3 (https://github.com/unjs/rou3/issues/108) and already released as 0.x

**Comment by pmbanugo** [comment]
Got it, thanks. 

> Yep. Also h3 itself in v2 will be web native so numbers for Bun/Deno will definitely change 🚀

Does your comment above refer to v2 for h3? I wasn't sure which v2 you meant

**Comment by pi0** [comment]
confusing numbers sorry! 


- radix3 v1 is latest release of it
- the work that was supposed to evolve as radix3 v2, is being published as new package (rou3) with new versioning starting from 0

H3 v2, will use rou3 for it's rouer.

**Comment by pmbanugo** [comment]
Thanks for the clarification
