### ISSUE TITLE
Cannot read property 'entries' of undefined

### ISSUE THREAD

**Issue by hymair** [unjs/rou3#99]
### Environment

Node 20
Nuxt 3
Radix 1.1.1

### Reproduction

Let me know if you need any more info from the sentry issue and I will provide it.

![image](https://github.com/unjs/radix3/assets/21025134/9df94df0-9574-436b-ac7f-96e616dde2d5)

### Describe the bug

This is from a Nuxt 3 generated static app. We've received a few Sentry reports with this error.

**Comment by pi0** [comment]
Hi. With new rou3 implementation, this should not happen. But feel free to raise a PR to fix legacy `radix3` branch.
